### PR TITLE
Make fixed tags order

### PR DESCRIPTION
**Pull request by bozaro**
Unfortunately map type in go has no stable order. In this case same tags can generate differ `tags` field value.

### CODE REVIEW

**Comment by mkevac** [comment]
@bozaro why is it important?

**Comment by bozaro** [comment]
Unfortunatelly dictionary in golang is unordered.
So, differ instances of same application send same tags in differ orider. In pimba tags map present as string.
As result I have in pimba many lines with tags like:
```
rev=abcde123,build=release,group=endpoints
build=release,rev=abcde123,group=endpoints
build=release,group=endpoints,rev=abcde123
group=endpoints,build=release,rev=abcde123
group=endpoints,rev=abcde123,build=release
rev=abcde123,group=endpoints,build=release
```
But I prefer to have one tags value.

**Comment by mkevac** [comment]
Are you talking about piNba? (with N) This one http://pinba.org/?
Because I asked the author and some other people and they tend to agree that there should be no difference in which order we are sending this data.

**Comment by bozaro** [comment]
Yes. I talk about pinba. Sorry for typo.
I really have differ tags from one application. May be internally this is not so important, but it looks like inaccurately.

**Comment by mkevac** [comment]
I don't think it is a good idea to add sorting here just for fixing inaccuracy, sorry.
Seems that servers (both pinba and pinba2) do not care about ordering.

**Pull request closed without merging**
